language: node_js
sudo: false 
cache: 
  apt: true
  directories:
    - node_modules
node_js:
- '0.10'
addons:
  apt:
    packages:
    - redis-server
    - libcairo2-dev
    - libpixman-1-dev
    - libpango1.0-dev
    - libjpeg-dev
    - libgif-dev
before_script:
- npm install -g grunt-cli
